[2024-06-03 14:25:07,330] 181 apscheduler.scheduler - INFO -Scheduler started
[2024-06-03 14:25:10,953] 21 root - INFO -starting data ingestion
[2024-06-03 14:25:10,954] 27 root - INFO -Exporting data from casandra to feature store 
[2024-06-03 14:25:13,283] 1703 cassandra.cluster - WARNING -Downgrading core protocol version from 66 to 65 for e4d5a3c1-e93d-4762-b366-9ba2252f22f5-eu-west-1.db.astra.datastax.com:29042:9e3a5bee-3d95-3bf7-90f5-09bd2177324b. To avoid this, it is best practice to explicitly set Cluster(protocol_version) to the version supported by your cluster. http://datastax.github.io/python-driver/api/cassandra/cluster.html#cassandra.cluster.Cluster.protocol_version
[2024-06-03 14:25:14,559] 1703 cassandra.cluster - WARNING -Downgrading core protocol version from 65 to 5 for e4d5a3c1-e93d-4762-b366-9ba2252f22f5-eu-west-1.db.astra.datastax.com:29042:9e3a5bee-3d95-3bf7-90f5-09bd2177324b. To avoid this, it is best practice to explicitly set Cluster(protocol_version) to the version supported by your cluster. http://datastax.github.io/python-driver/api/cassandra/cluster.html#cassandra.cluster.Cluster.protocol_version
[2024-06-03 14:25:16,164] 1703 cassandra.cluster - WARNING -Downgrading core protocol version from 5 to 4 for e4d5a3c1-e93d-4762-b366-9ba2252f22f5-eu-west-1.db.astra.datastax.com:29042:9e3a5bee-3d95-3bf7-90f5-09bd2177324b. To avoid this, it is best practice to explicitly set Cluster(protocol_version) to the version supported by your cluster. http://datastax.github.io/python-driver/api/cassandra/cluster.html#cassandra.cluster.Cluster.protocol_version
[2024-06-03 14:25:19,081] 292 cassandra.policies - INFO -Using datacenter 'eu-west-1' for DCAwareRoundRobinPolicy (via host 'e4d5a3c1-e93d-4762-b366-9ba2252f22f5-eu-west-1.db.astra.datastax.com:29042:9e3a5bee-3d95-3bf7-90f5-09bd2177324b'); if incorrect, please specify a local_dc to the constructor, or limit contact points to local cluster nodes
[2024-06-03 14:25:19,082] 3863 cassandra.cluster - WARNING -Found multiple hosts with the same endpoint (e4d5a3c1-e93d-4762-b366-9ba2252f22f5-eu-west-1.db.astra.datastax.com:29042:9e3a5bee-3d95-3bf7-90f5-09bd2177324b). Excluding peer 10.0.0.6
[2024-06-03 14:25:19,083] 2126 cassandra.cluster - INFO -Cassandra host e4d5a3c1-e93d-4762-b366-9ba2252f22f5-eu-west-1.db.astra.datastax.com:29042:00694036-11ec-39fb-8238-d79afd9b0e46 removed
[2024-06-03 14:25:24,424] 36 root - INFO -artifact-datainjection folder created 
[2024-06-03 14:25:24,433] 45 root - INFO -performed train test split on dataframe
[2024-06-03 14:25:24,433] 46 root - INFO -exited split_data as train test split
[2024-06-03 14:25:24,434] 51 root - INFO -exporting train and test file path
[2024-06-03 14:25:24,439] 56 root - INFO -exported train and test file path
[2024-06-03 14:25:24,439] 25 root - INFO -Data ingestion completed and artifact
[2024-06-03 14:25:24,440] 26 root - INFO -Data ingestion completed and artifact: DataIngestionArtifact(trained_file_path='artifact\\06_03_2024_14_25_00\\data_ingestion\\ingested\\train.csv')
[2024-06-03 14:25:24,536] 25 root - INFO -Required number of columns: 5
[2024-06-03 14:25:24,536] 26 root - INFO -Data frame has columns: 5
[2024-06-03 14:25:24,537] 45 root - INFO -Missing numerical columns: [[]]
[2024-06-03 14:25:24,537] 133 root - INFO -Data validation artifact: DataValidationArtifact(validation_status=True, valid_train_file_path='artifact\\06_03_2024_14_25_00\\data_ingestion\\ingested\\train.csv', invalid_train_file_path=None, invalid_test_file_path=None, drift_report_file_path='artifact\\06_03_2024_14_25_00\\data_validation\\drift_report\\report.yaml')
[2024-06-03 14:25:24,537] 1745 main - ERROR -Exception on /train [GET]
Traceback (most recent call last):
  File "C:\Users\DELL\anaconda3\envs\pythonProject5\lib\site-packages\flask\app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\DELL\anaconda3\envs\pythonProject5\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\DELL\anaconda3\envs\pythonProject5\lib\site-packages\flask_cors\extension.py", line 178, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\DELL\anaconda3\envs\pythonProject5\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\DELL\anaconda3\envs\pythonProject5\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\DELL\anaconda3\envs\pythonProject5\lib\site-packages\flask_cors\decorator.py", line 130, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "C:\Users\DELL\anaconda3\envs\pythonProject5\lib\site-packages\flask\helpers.py", line 209, in make_response
    return current_app.make_response(args)  # type: ignore
  File "C:\Users\DELL\anaconda3\envs\pythonProject5\lib\site-packages\flask\app.py", line 2139, in make_response
    f"The view function for {request.endpoint!r} did not"
TypeError: The view function for 'trainRouteClient' did not return a valid response. The function either returned None or ended without a return statement.
[2024-06-03 14:42:18,002] 212 apscheduler.scheduler - INFO -Scheduler has been shut down
